### ISSUE TITLE
IINFOGRAFIA 

### ISSUE THREAD

**Issue by lizzeth99** [SistemasTecTlaxiaco/infografia-lizzeth99-1#2]
[INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lizzeth99-1/files/7151427/INFOGRAFIA.pdf)

**Comment by Brendalp** [comment]
calificación =18

**Comment by josealfredo79** [comment]
Faltan las metodologías, faltan las herramientas... para la proxima si no se realiza un buen trabajo se tendra que hacer nuevamente.
